
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ABIMBOLA PC
 */
public class chatmain2 extends javax.swing.JFrame {

    /**
     * Creates new form Chatmain
     */
    public chatmain2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tArea = new javax.swing.JTextArea();
        tMessage = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Group 7 AI Chat Box");

        tArea.setColumns(20);
        tArea.setRows(5);
        jScrollPane1.setViewportView(tArea);

        tMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMessageActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>                        
    String area = "";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String message = tMessage.getText();
        String message1 = tArea.getText();
//        if(message.equals("Admission")){
//            
//            
//             tArea.setText("Me:"+message1+"\n"+"Me:"+message+"\n"+"Chatbot: Welcome to the admission portal");
//        tMessage.setText("");
//        }else if(message.equals("Payment")){
//            
//            
//             tArea.setText("Me:"+message1+"\n"+"Me:"+message+"\n"+"Chatbot: The school fees is high");
//        tMessage.setText("");
//        }else if(message.equals("bank")){
//            
//            
//             tArea.setText("Me:"+message1+"\n"+"Me:"+message+"\n"+"Chatbot: You can pay in UI Microfinance bank");
//        tMessage.setText("");
//        }
       

//        ArrayList<String> ars = new ArrayList<>();
//        ars.add("Emmanuel");
//        ars.add("Oluchukwu");
//        
//        JOptionPane.showMessageDialog(this, ars);
            
        String txt = tMessage.getText();
        tArea.setText(area+"\nMe => "+txt+"\n");
        area = tArea.getText();
        
        
        String arr[] = {};
        arr = txt.split(" ");
        //JOptionPane.showMessageDialog(this, arr);
        
        Map states = new HashMap();
        states.put("Admission", "Visit the PostGraduaute School for details");
        states.put("Payment", "You can pay at UI Micro Finance Bank");
        states.put("Visa", "Visit Nigerian Embassy in your Country");
        
        for(int i=0; i<arr.length; i++){
            if(arr[i].equals("Admission")){
                tArea.setText(area + "\nChatBot => "+states.get("Admission").toString());
            }
            else if(arr[i].equals("Payment")){
                tArea.setText(area + "\nChatBot => "+states.get("Payment").toString());
            }
            else if(arr[i].equals("Visa")){
                tArea.setText(area + "\nChatBot => "+states.get("Visa").toString());
            }
            else{
                tArea.setText(area + "\nChatBot => Sorry I dont understand what you are saying");
            }
        }
        
//        if(arr.toString().contains("Admission")){
//            tArea.setText(states.get("Admission").toString());
//        }
//        else if(arr.toString().contains("Payment")){
//            tArea.setText(states.get("Payment").toString());
//        }
//        else if(arr.toString().contains("Visa")){
//            tArea.setText(states.get("Visa").toString());
//        }
//        else{
//            tArea.setText("Sorry I dont understand what you are saying");
//        }
    }                                        
       
    private void tMessageActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
       
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chatmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chatmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chatmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chatmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chatmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tArea;
    private javax.swing.JTextField tMessage;
    // End of variables declaration                   
}
